baseURL = 'https://distraction.engineer/'
languageCode = 'en-us'
theme = 'distraction'

title = 'the.Distraction.Engineer'
params.description = 'a notebook and blog by Mike Kasprzak'
copyright = 'Mike Kasprzak'

enableEmoji = true
enableRobotsTXT = true
