baseURL = 'https://the.distraction.engineer/'
languageCode = 'en-us'

title = 'the.Distraction.Engineer'
copyright = 'Mike Kasprzak'
params.description = 'a notebook and blog by Mike Kasprzak'

enableEmoji = true
enableRobotsTXT = true

[markup.goldmark]
# Enable markdown {attributes} feature on block elements
parser.attribute.block = true
# Disable wrapping of standalone images in <p> tags
parser.wrapStandAloneImageWithinParagraph = false
