baseURL = 'https://the.distraction.engineer/'
theme = 'distraction'

title = 'the.Distraction.Engineer'
copyright = 'Mike Kasprzak'
params.description = 'a notebook and blog by Mike Kasprzak'

# see themes/distraction/hugo.toml for theme configuration
